# Generated by Django 5.0.2 on 2024-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0006_category_alter_customer_id_alter_feedback_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
